### ISSUE TITLE
Initial searching gives a 500 null exception

### ISSUE THREAD

**Issue by ivohuisjes** [ConsenSys/IPFS-Store#49]
When I have not yet indexed any files and the index doesn't exists, the (rest)server return a 500 null exception. 
I used the Java API in IPFSStore.java to call the IPFS endpoint (Page<Metadata> search(String indexName, Query query, Pageable pageable))

`2018-11-20 15:27:55.008 DEBUG 20086 --- [io-8080-exec-10] c.t.i.i.c.j.w.i.RestIPFSStoreWrapperImpl : Search [indexName=documents, query=Query(filterClauses=[Filter(name=author, names=[author], operation=equals, value=id1)])]
2018-11-20 15:27:55.022 TRACE 20086 --- [io-8080-exec-10] c.t.i.i.c.j.w.i.RestIPFSStoreWrapperImpl : url=http://ipfs-vbox:8040/ipfs-store/query/search?index=documents
2018-11-20 15:27:55.022 TRACE 20086 --- [io-8080-exec-10] c.t.i.i.c.j.w.i.RestIPFSStoreWrapperImpl : query=Query(filterClauses=[Filter(name=author, names=[author], operation=equals, value=id1)])
2018-11-20 15:27:56.281 ERROR 20086 --- [io-8080-exec-10] c.t.i.i.c.j.w.i.RestIPFSStoreWrapperImpl : Error while searching [indexName=documents, query=Query(filterClauses=[Filter(name=author, names=[author], operation=equals, value=id1)])]

org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 null
	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:79) ~[spring-web-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:99) ~[spring-web-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79) ~[spring-web-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:777) ~[spring-web-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:735) ~[spring-web-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:709) ~[spring-web-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:627) ~[spring-web-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at net.consensys.tools.ipfs.ipfsstore.client.java.wrapper.impl.RestIPFSStoreWrapperImpl.search(RestIPFSStoreWrapperImpl.java:276) ~[ipfs-store-client-java-v0.1.7.jar:0.1.7]
	at net.consensys.tools.ipfs.ipfsstore.client.java.IPFSStore.search(IPFSStore.java:367) [ipfs-store-client-java-v0.1.7.jar:0.1.7]
	at net.consensys.tools.ipfs.ipfsstore.client.java.IPFSStore.search(IPFSStore.java:354) [ipfs-store-client-java-v0.1.7.jar:0.1.7]
	at nl.enshore.hackathon.backend.service.FileService.getTotalElements(FileService.java:251) [classes/:na]`

I would expect the rest-service to return not-found or similar

I tested version IPFS-store v0.17

**Comment by gjeanmart** [comment]
Hey,
Again thank you for reporting those issues. This is super useful !

This is a actually known issue which might need to be documented. Basically it's not possible execute a query on an index that doesn't exist. But when you index a document, the index is automatically created if it doesn't exist yet.

What I do in the `spring-data-ipfsstore` adapter for example is to call the function `IPFSStore.createIndex("documents")` in the constructor of my service. So before everything, I make sure the index exists.

**Comment by gjeanmart** [comment]
**Release: 0.1.16**
When instantiating the Java client, we can now pass a list of indexes to create (if not existing beforehand).

`IPFSStore client = new IPFSStore("http://localhost:8040/", "index1", "index2", "indexn");`
